### ISSUE TITLE
handling of unsigned values

### ISSUE THREAD

**Issue by qschneider** [the78mole/esphome_components#11]
MSHK1, MSHK2 and all temperatures that could have a negative value should be treated as signed values not as unsigned to get usable values. These values are  formated in two's complement.

**Comment by jensgraef** [comment]
Hi @qschneider - thanks for the hint - we were already thinking that there must be a way for those values to get negative.
I'll change the parsing for those.

**Comment by jensgraef** [comment]
I've opened pull request #15 to address this. @qschneider Would you mind having a look whether I found all relevant values?

**Comment by qschneider** [comment]
do you think it's necessary to define more sensors besides AT, ATD, MSHK1 and MSHK2 as signed integers?
Fi ABTMP will never reach negative values and some others like BET or BAT might not get greater than 127, but that doesn't mean their values are processed in the twos complement. Besides that at least MSHK2 works as expected.

**Comment by jensgraef** [comment]
I added a commit - now only AT, ATD, MSHK1 and MSHK2 are interpreted as signed integers.
