### ISSUE TITLE
device class of mixer_position 

### ISSUE THREAD

**Issue by qschneider** [the78mole/esphome_components#12]
heating_circuit_1_mixer_position and heating_circuit_2_mixer_position have the device_class=DEVICE_CLASS_TEMPERATURE.
I'am not sure which device_class would be appropriate, or if it could be omitted if nothing matches.

https://www.home-assistant.io/integrations/sensor/

**Comment by Bascht74** [comment]
mixer and pump shouldn't have that device class. 
They could have "power factor" (in %) or no device_class at all. For me they should have no device class at all.

**Comment by jensgraef** [comment]
I agree.
@qschneider / @Bascht74 : Would one you you like to create a pull request for that? The device classes are configured in sensor.py

**Comment by Bascht74** [comment]
@jensgraef I just made a pull request for that and some more little changes to sensors and binary sensors (e.g add the entity category).

If you make an example how to add the entity category for switch and number I could add them there, too.

**Comment by Bascht74** [comment]
@qschneider Can you check?

**Comment by qschneider** [comment]
Hi, seems to me everything works fine, except the seperation between entity_category=ENTITY_CATEGORY_DIAGNOSTIC and entity_category=ENTITY_CATEGORY_NONE. To me (personally) i wouldn't expect values in the diagnostic section, rather they belong in the sensors section.  
<img width="332" alt="Bildschirmfoto 2022-12-10 um 11 46 37" src="https://user-images.githubusercontent.com/3471813/206851381-327d8fbd-bf9f-4e6b-918f-06f6fa651f47.png">
<img width="391" alt="Bildschirmfoto 2022-12-10 um 11 46 27" src="https://user-images.githubusercontent.com/3471813/206851383-f0e86dfa-a19f-4688-a755-2591a4f4ecf4.png">

**Comment by Bascht74** [comment]
For me diagnostic entities are the ones that are not primary and/or don't do measurements itself. You just use them to see whether your system is working in the right way.

according to: 
https://developers.home-assistant.io/docs/core/entity/

`Classification of a non-primary entity. 
Set to config for an entity which allows `changing the configuration of a device`, for example a switch entity making it possible to turn the background illumination of a switch on and off. 
Set to diagnostic for an entity `exposing some configuration parameter or diagnostics of a device but does not allow changing it`, for example a sensor showing RSSI or MAC-address.`

so the number and select entities should move to config entities. 

At the long end the primary entities should stay at `none`.  
E.g. main temperatures that are measured and climate entities for WW, HK1 and HK2.

So if you are distracted by splitting the sensors we should move more of them to the diagnostic entities section as they are not "primary". 
E.g. you don't get in touch with the Kesselvorlaufisttemperatur directly and the Brennerausschalttemperatur and Brennereinschalttemperatur, they are just diagnostic data.
On the other side, the WarmwasserIstTemperatur is a primary entity as the water come out of your tab with that temperature...

Besides that you normally add entities to your dashboards. you usually don't work that much with the device section in HA.

**Comment by qschneider** [comment]
Mhh, it all is how you interpret
"Set to diagnostic for an entity exposing some configuration parameter or diagnostics of a device but does not allow changing it, for example a sensor showing RSSI or MAC-address"

So i would interpret it that way - put data in the diagnostic section which are related to the HW device itself, km271 or 2107. All others are sensor data that may change after user intervention, by time schedule or by the heater itself.

But i'am not keen on it, so it could stay that way unless someone else gets confused.

**Comment by Bascht74** [comment]
OK, then we should leave it by now until we have more entities (e.g. more binary entities, sensor entities and control entities). 

For me the main output of the Buderus is warm water that has a specific temperature and Heating Water that has a specific temperature and a pump to get it to the radiators. These are the primary entities. 

All other are diagnostic and are used by km271/2107-system to control the system to produce these two primary entities.

**Comment by Bascht74** [comment]
@jensgraef @the78mole you can close the issue.
