### ISSUE TITLE
Something goes wrong with Tag/Nacht/Auto select and switch

### ISSUE THREAD

**Issue by the78mole** [the78mole/esphome_components#14]
When
https://github.com/the78mole/esphome_components/blob/1e22700df003cdebacc8df02c068563535ee4a12/components/km271_wifi/km271_params.cpp#L89

is executed by the param 0x0085 (short after initialization) , it shows quite wired trash...

![image](https://user-images.githubusercontent.com/7723396/205995809-7600424c-eebc-46c1-b5ed-bb45f76332b5.png)

I doubt, that data does not contain chars... 

When I change the switch, everything seems fine (ON, OFF, no trash).

![image](https://user-images.githubusercontent.com/7723396/205996809-59e3c6d2-0931-4dbd-b7b7-9aac6eef1e30.png)

Need to digg into it a bit deeper...

**Comment by jensgraef** [comment]
I think it's wrong to print it as a string - that log line is something left over from some attempts before.
The configuration value is encoded as 0/1/2.
Is there something wrong beyond log line?

**Comment by the78mole** [comment]
I didn't setup the select yet, so I can't tell if it's OK. But the switch seems to work as expected.

**Comment by the78mole** [comment]
When using the select, I do not see the wired line of debug anymore, even if the debugging output line of code still exists. I'll try to change it, to get a reasonable output and create some PR.

**Comment by qschneider** [comment]
Do you still get the weird values?

**Comment by the78mole** [comment]
No, because I do not use the switch anymore. I use the select with lambda. But in fact, the line is wrong and if somebody uses the switch, he/she will get the crazy stuff an possibly the module will panic and reboot (infinitely). I created a PR :-)

**Comment by the78mole** [comment]
#23 is handling this...
