### ISSUE TITLE
thoughts on naming schema in buderus-km271.yaml

### ISSUE THREAD

**Issue by qschneider** [the78mole/esphome_components#16]
Playing around with the entities in HA i stumbled over the naming schema of some entities.
If we just provide a name and not an id, HA will generate an entity_id of the name which is misleading sometimes.
So it might be better for user experience if we define ids AND names, so entity naming could be changed to some other language without changing the entity_ids.

- Außentemperatur vs Gedaempfte Aussentemperatur
either use german Umlaute, or use "Aussentemperatur" for both of them, because if you use entity completion in HA you might got confused.

- HK2 Heizkurve +10 °C and HK2 Heizkurve -10 °C
both of the above result in sensor.hk2_heizkurve_10_degc , the later one with a trailing _2 so you can't tell by the entitiy_id which is which.

**Comment by Bascht74** [comment]
Is the espHome id really feeding HA with the entity name?
In my last attempts HA takes the name out of the entity name and not the id. Maybe they changed it...

Could you double check with a new entity that has a name & id that is completely different. Then check what the name and entity id is in HA.

**Comment by Bascht74** [comment]
> So it might be better for user experience if we define ids AND names, so entity naming could be changed to some other language without changing the entity_ids.

You can add the id to your config, e.g.

```
    boiler_target_temperature:
      name: "Kesselvorlaufsolltemperatur"
      id: something_you_name_it
```

**Comment by Bascht74** [comment]
I checked it: 

```
number:
  - platform: template
    id: warmwasser_Temperatur
    name: "Warmwassersolltemperatur Tag"
```
will be in HA: 
`number.warmwassersolltemperatur_tag`
and not
`number.warmwasser_temperatur`

same for you?

**Comment by qschneider** [comment]
Yes, sadly you are right! Searching for it i found your Feature requesthttps://github.com/esphome/feature-requests/issues/1741 and this https://github.com/home-assistant/core/issues/47546 . Too bad that we use an id: in esphome that isn't recognized in HA nor it is wished.
So we have to choose names that differ enough in HA to be self explaining.

**Comment by qschneider** [comment]
resolved in #12 and #22 so we could close here ?

**Comment by qschneider** [comment]
to reflect the changes in the PR we should also rename the corresponding esphome yaml.
For example like this.

    heating_circuit_1_curve_p10:
      name: "HK1 Heizkurve 10 °C"
    heating_circuit_1_curve_0:
      name: "HK1 Heizkurve 0 °C"
    heating_circuit_1_curve_n10:
      name: "HK1 Heizkurve 10 °C minus"
and
      name: "HK2 Heizkurve 10 °C"
    heating_circuit_2_curve_0:
      name: "HK2 Heizkurve 0 °C"
    heating_circuit_2_curve_n10:
      name: "HK2 Heizkurve 10 °C minus"

**Comment by Bascht74** [comment]
Hi @qschneider, 

I am fine with how they are, because they are just an example in the yaml code. So you can name it as you like and they stay the same, even if the code here changes...

**Comment by the78mole** [comment]
Lets close it. Its just make up 😜
