### ISSUE TITLE
Heavy logging of some parameters

### ISSUE THREAD

**Issue by the78mole** [the78mole/esphome_components#37]
Logs shows some parameters continuously

![image](https://user-images.githubusercontent.com/7723396/208361943-e718b685-3589-4aa2-8f5c-0618c2981814.png)

**Comment by qschneider** [comment]
0x0400, 0x882E, 0x882F are values that seem to have high occurrence and no meaning.

**Comment by jensgraef** [comment]
In PR #39 I changed the code to ignore telegrams for those three parameters

**Comment by qschneider** [comment]
can we close here because of https://github.com/the78mole/esphome_components/pull/39 ?
