### ISSUE TITLE
signed values broken in #43?

### ISSUE THREAD

**Issue by qschneider** [the78mole/esphome_components#44]
I tried the Christmas release :-) and besides Mischer HK2 everything seems to be ok.

<img width="496" alt="Bildschirmfoto 2022-12-25 um 14 18 42" src="https://user-images.githubusercontent.com/3471813/209469560-11dd256a-2ffe-419a-baa7-f2f893202514.png">

[logs_esp32-km271-hz_upload.txt.zip](https://github.com/the78mole/esphome_components/files/10300006/logs_esp32-km271-hz_upload.txt.zip)

Merry Christmas !

**Comment by jensgraef** [comment]
Merry Christmas to you, too!
I've created #45  to fix it.

**Comment by jensgraef** [comment]
fixed with merge of #45
