### ISSUE TITLE
UNSIGNED_INT_DIVIDED_BY_2 not handling .5°C values

### ISSUE THREAD

**Issue by qschneider** [the78mole/esphome_components#49]
I found out that rather than just dividing those values by 2, they seem to have the purpose to display 0.5 step temperatures as a float value.

This should be the case for   
    heating_circuit_1_room_target_temperature, RSTHK1
    heating_circuit_1_room_temperature, RITHK1
    heating_circuit_2_room_target_temperature, RSTHK2
    heating_circuit_2_room_temperature, RITHK2

at the moment I have also an issue with heating_circuit_2_room_temperature as it is displaying 55,0°C but it shouldn't.
maybe this is related ?

**Comment by qschneider** [comment]
maybe the code is working fine because i found this in my log.

    [21:12:06][D][km271:036]: Parameter 0x8117: (Data: 1, 0x6E )
    [21:12:06][D][sensor:127]: 'HK2 Raumisttemperatur': Sending state 55.00000 °C with 1 decimals of accuracy

still it's unclear to me how to handle this value, because no room thermostat is attached...

**Comment by jensgraef** [comment]
Could you clarify on that issue regarding the code not handling values ending in .5°C?
It seems to be working fine at my installation:
![image](https://user-images.githubusercontent.com/10597919/211087909-42d217d1-90e0-419c-9302-3da9e28f3a84.png)
