### ISSUE TITLE
Updating ESPHome Itself

### ISSUE THREAD

**Issue by AlexKusnezov** [the78mole/esphome_components#69]
Hey guys,

I'm kind of new to ESPHome and wanted to ask how it is with the updates of the framework itself in relation to this firmware.

Currently I'm on 2023.4.4 and want to update to 2023.5.5. Is it safe to do that by just hitting the upadte button?
<img width="792" alt="Screenshot 2023-06-02 at 09 06 32" src="https://github.com/the78mole/esphome_components/assets/33514406/e46fce8d-3e82-4040-94f6-63874fb8b92b">
Or does it have to be some kind of apporved by you guys first?

Sorry for being overconcerned here ;)

**Comment by the78mole** [comment]
Should not be a problem. I can not guarantee, that the APIs we use keep untouched, but up to now, we never had issues. 
We also try to not take over every cool new feature of new base firmwares, to not break our component for people still using not up-to-date ESPhome addon.

**Comment by AlexKusnezov** [comment]
hey just wanted to report, that meanwhile I've successfully updated to Esphome 2023.7.0 and everything is good.
![Screenshot_20230729-125708_Home Assistant](https://github.com/the78mole/esphome_components/assets/33514406/3698a25f-02c7-4808-b5c1-7a135946f718)

**Comment by AlexKusnezov** [comment]
2023.12.9 and still going:
<img width="508" alt="Screenshot 2024-01-25 at 09 16 26" src="https://github.com/the78mole/esphome_components/assets/33514406/300c02d8-ef53-457e-b578-d14a72b1a521">
