### ISSUE TITLE
Slider (km271_hk1_urlaubstage + km271_hk2_urlaubstage)

### ISSUE THREAD

**Issue by dansh1n** [the78mole/esphome_components#71]
Hello, thanks for your work. To set the holidays, you need to pass it on the hk1 and hk2 circuits, can you somehow combine this into one slider (km271_hk1_urlaubstage + km271_hk2_urlaubstage)?

**Comment by the78mole** [comment]
Combining it in the component is not the right way to do it. You could define your own [Number Template](https://esphome.io/components/number/template) in the ESPhome YAML config and set both number values of the km271 in a lambda of your template. Another possibility is to use an automation in Home Assitant with some helper integration to achieve the same.
