### ISSUE TITLE
Error Update ESPHome 2024.6.1

### ISSUE THREAD

**Issue by hergie1976** [the78mole/esphome_components#77]
I get the following error in ESPHome 2024.6.1 when i update KM wirelessly

INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/buderus-heizung.yaml...
INFO Updating https://github.com/the78mole/esphome_components.git@main
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

At least one platform must be specified for 'ota'; add 'platform: esphome' for original OTA functionality

**Comment by Markus1971a** [comment]
Unfortunately I have the same problem, but also since version 2024.6.0

**Comment by hergie1976** [comment]
Hi,

you have to change the config.

Insert the following part in the config yaml. Please use the editor of ESPHome!

```
ota:
  platform: esphome
```

Best Regrads

Heiko

**Comment by the78mole** [comment]
Thanks Heiko 🤗
